apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  selector:
    app: openldap
  type: ClusterIP
  ports:
    - name: http-1389
      protocol: TCP
      port: 1389
      targetPort: 1389
    - name: http-1636
      protocol: TCP
      port: 1636
      targetPort: 1636