apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: assistmai
  name: assistmai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistmai
  template:
    metadata:
      labels:
        app: assistmai
    spec:
      containers:
      - image: nblotti/assistmeai
        name: chat
        resources:
          limits:
            memory: 500Mi
        volumeMounts:
          - mountPath: /app/config
            name: config-volume
        ports:
        - containerPort: 8080
          name: http
      volumes:
        - configMap:
            defaultMode: 420
            name: assistme-config
          name: config-volume
      automountServiceAccountToken: false
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
