# Generated by Django 3.2.23 on 2024-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('fire_base_token', models.CharField(max_length=50)),
            ],
        ),
    ]
