# Generated by Django 3.2.23 on 2024-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Downloaded'), ('3', 'Transcribed'), ('4', 'FirebaseSent')], default='1', max_length=2),
        ),
    ]
