# Generated by Django 3.2.23 on 2024-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistme', '0002_transcript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='firebase_message_data_sent',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='firebase_message_result',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
