# Generated by Django 3.2.23 on 2024-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistme', '0003_auto_20240118_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='error_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
